// Fill out your copyright notice in the Description page of Project Settings.

#include "AnimGraphNode_MyCompilerDefaults.h"

UAnimGraphNode_MyCompilerDefaults::UAnimGraphNode_MyCompilerDefaults(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}

UAnimGraphNode_MyCompilerDefaults::~UAnimGraphNode_MyCompilerDefaults()
{
	
}

void UAnimGraphNode_MyCompilerDefaults::OnProcessDuringCompilation(IAnimBlueprintCompilationContext& InCompilationContext, IAnimBlueprintGeneratedClassCompiledData& OutCompiledData)
{
	//UAnimGraphNode_MyCompilerDefaults* cdo= this->GetClass()->GetDefaultObject<UAnimGraphNode_MyCompilerDefaults>();
	//cdo->Node.MyString=TEXT("This is generated by compiler.");
	//cdo->Node.MyString_CompilerDefaults=TEXT("This is generated by compiler.");

	Node.MyString=TEXT("This is generated by compiler.");
	Node.MyString_CompilerDefaults=TEXT("This is generated by compiler.");
}
